# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

# publish-commit-azure-queue pipeline

trigger: [ test-main ]

stages:
- stage: Push to Azure Queue
  condition: ne(github.event.label.name, 'do-not-merge-in-next')
  jobs:
    - job: queue-commits
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - script: |
          const connectionString = ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }};
          const queueName = ${{ secrets.AZURE_QUEUE_NAME }}
          const queueServiceClient = QueueServiceClient.fromConnectionString(connectionString);
          const queueClient = queueServiceClient.getQueueClient(queueName);
          const message = {
            sha: '${{ github.event.pull_request.head.sha }}',
            url: '${{ github.event.url }}'
            assignee: '${{ github.author }}',
            label: 'queued',
            run_id: '${{ github.run_id }}'
          };
          await queueClient.sendMessage(JSON.stringify(message));
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.number,
            body: "Commit queued for merging with next branch. Please ignore this comment it for now."
          })

# add a wiki link later on
